add support for list values
seek-oss/kpt-functions pull request #28
Opened 2021-05-03 01:18 UTC by mper0003

2021-05-03 02:57 UTC, Niksko requested changes
Looks good, but can we add a test for this please

2021-05-03 10:16 UTC, mper0003 commented
> Looks good, but can we add a test for this please

Added tests around setting  a`value` and `listValues`.

2021-05-03 21:22 UTC, ashlineldridge approved these changes
Awesome work 👏🏼

2021-05-03 21:22 UTC, ashlineldridge commented on pkg/filters/set.go
> +		}
🥇

2021-05-04 05:27 UTC, Niksko approved these changes
Great, looks good to me too!

2021-05-04 05:29 UTC, merged